name: Test Databricks Token Federation

on: 
  workflow_dispatch  # Permite ejecutar manualmente

permissions:
  id-token: write    # ¡SÚPER IMPORTANTE!
  contents: read

jobs:
  test-databricks:
    runs-on: ubuntu-latest
    environment: prod  # DEBE coincidir con el environment creado
    
    env:
      DATABRICKS_AUTH_TYPE: github-oidc-azure
      DATABRICKS_HOST: https://accounts.azuredatabricks.net
      DATABRICKS_ACCOUNT_ID: 5955cca0-8ac1-4e1f-b284-cdab0a302c45
      DATABRICKS_CLIENT_ID: a9ed4ecc-deab-4e2a-97b2-2ab9f2e5f09e
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Databricks CLI
        uses: databricks/setup-cli@main
      
      - name: Test - Show service principal info
        run: databricks account service-principals get 142053800559278
        
      - name: Test - List workspaces
        run: databricks account workspaces list || echo "No workspaces found"
        
      - name: Test - List account users
        run: databricks account users list --limit 5 || echo "No permission to list users"
        
      - name: Success message
        run: echo "🎉 Token Federation funciona correctamente!"
